export const FETCH_HABITS_PENDING = 'FETCH_HABITS_PENDING';
export const FETCH_HABITS_SUCCESS = 'FETCH_HABITS_SUCCESS';
export const FETCH_HABITS_ERROR = 'FETCH_HABITS_ERROR';

export const ADD_HABIT_PENDING = 'ADD_HABIT_PENDING';
export const ADD_HABIT_SUCCESS = 'ADD_HABIT_SUCCESS';
export const ADD_HABIT_ERROR = 'ADD_HABIT_ERROR';

export const SINGLE_HABIT_PENDING = 'SINGLE_HABIT_PENDING';
export const SINGLE_HABIT_SUCCESS = 'SINGLE_HABIT_SUCCESS';
export const SINGLE_HABIT_ERROR = 'SINGLE_HABIT_ERROR';

export const UPDATE_HABIT_PENDING = 'UPDATE_HABIT_PENDING';
export const UPDATE_HABIT_SUCCESS = 'UPDATE_HABIT_SUCCESS';
export const UPDATE_HABIT_ERROR = 'UPDATE_HABIT_ERROR';

export const DELETE_HABIT_PENDING = 'DELETE_HABIT_PENDING';
export const DELETE_HABIT_SUCCESS = 'DELETE_HABIT_SUCCESS';
export const DELETE_HABIT_ERROR = 'DELETE_HABIT_ERROR';

export const FETCH_MEASURE_PENDING = 'FETCH_MEASURE_PENDING';
export const FETCH_MEASURE_SUCCESS = 'FETCH_MEASURE_SUCCESS';
export const FETCH_MEASURE_ERROR = 'FETCH_MEASURE_ERROR';

export const ADD_MEASURE_PENDING = 'ADD_MEASURE_PENDING';
export const ADD_MEASURE_SUCCESS = 'ADD_MEASURE_SUCCESS';
export const ADD_MEASURE_ERROR = 'ADD_MEASURE_ERROR';

export const SINGLE_MEASURE_PENDING = 'SINGLE_MEASURE_PENDING';
export const SINGLE_MEASURE_SUCCESS = 'SINGLE_MEASURE_SUCCESS';
export const SINGLE_MEASURE_ERROR = 'SINGLE_MEASURE_ERROR';

export const UPDATE_MEASURE_PENDING = 'UPDATE_MEASURE_PENDING';
export const UPDATE_MEASURE_SUCCESS = 'UPDATE_MEASURE_SUCCESS';
export const UPDATE_MEASURE_ERROR = 'UPDATE_MEASURE_ERROR';

export const DELETE_MEASURE_PENDING = 'DELETE_MEASURE_PENDING';
export const DELETE_MEASURE_SUCCESS = 'DELETE_MEASURE_SUCCESS';
export const DELETE_MEASURE_ERROR = 'DELETE_MEASURE_ERROR';

export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_IN_PENDING = 'SIGN_IN_PENDING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
